### PR TITLE
add Terraform instructions

### PR DESCRIPTION
**Pull request by afeld**
Realizing I had never written it down. Hopefully a helpful starting point for https://github.com/18F/tts-tech-portfolio/issues/443.

### CODE REVIEW

**Comment by its-a-lisa-at-work** [comment]
Would be happy to co-work with someone on this to review

**Comment by amitfreeman-gov** [comment]
@afeld I've removed the step regarding obtaining latest terraform state as that just got merged to master.

**Comment by afeld** [comment]
Mind adding a note about the local AWS configuration, in that case?

**Comment by afeld** [comment]
Appears I can't approve my own pull request, but looks good to merge!

**Review by its-a-lisa-at-work — CHANGES_REQUESTED** [review]
Need help running through the directions for the first time; got stuck on Step 2

**Review by its-a-lisa-at-work — APPROVED** [review]
LGTM

@amitfreeman-gov thanks for the help!

**Pull request merged**
