### PR TITLE
add list of links about our domains

### PR DESCRIPTION
**Pull request by afeld**
Just learned about the GSA one through @afeijoo.

### CODE REVIEW

**Comment by afeld** [comment]
> What value are you thinking this will have to TTS for having this link here?

We sometimes get asked to do things across TTS domains, such as https://github.com/18F/tts-tech-portfolio/issues/753. This will help to be able to reference the canonical source.

Also, we should consider deprecating our subdomains list in favor of that one.

> Does TTS Tech Portfolio have any role or responsibility related to this list?

Yes in that we are responsible for the TTS domains within it. Similar level of responsibility for a number of other things that are linked from that file.

> Reluctant to link to something just because it is a good link

Why?

**Comment by afeld** [comment]
> unless it is something that we actively use

I mean, I didn't know it existed until just before creating this pull request, so too early to say 😉

**Comment by afeld** [comment]
Realizing that the GSA list is (or should be) a superset of the TTS one, so proposing we deprecate ours: https://github.com/18F/tts-tech-portfolio/issues/784

**Comment by its-a-lisa-at-work** [comment]
I think we need to get [acceptance of canonical source first ](https://github.com/18F/tts-tech-portfolio/issues/576)

> Reluctant to link to something just because it is a good link
> 
> Why?

Trying to be mindful of the [GSA Linking Policy](https://www.gsa.gov/website-information/website-policies#linking) and be as ruthless as possible to what we link to. 
That is one extra link that we're responsible for making sure stays up to date and folks might get the wrong impression that we own the data when we don't.

**Comment by afeld** [comment]
> links to information created and maintained by other public or private organizations

This means that the Linking Policy isn't applicable here, as this is a spreadsheet maintained by GSA.

> folks might get the wrong impression that we own the data when we don't

We are becoming co-owners. OSC was asking us to update that spreadsheet in the Digital Council meeting today.

**Pull request merged**
