### PR TITLE
use pull request board for Ops Rotation

### PR DESCRIPTION
**Pull request by afeld**
…instead of the saved search. One less thing to keep up to date.

### CODE REVIEW

**Comment by afeld** [comment]
@hoaiandang Were you able to confirm that it does?

**Comment by hoaiandang** [comment]
@afeld Just confirmed that it works (so long as we remember to assign the pull request to the project when we create it)!

**Comment by afeld** [comment]
Thanks for looking into it!

**Comment by afeld** [comment]
Part of https://github.com/18F/tts-tech-portfolio/issues/625, in having one less list of repositories to update.

**Comment by its-a-lisa-at-work** [comment]
I suggest we go back to the way it was before because the pull requests are not automatically getting added to the project board from the repos that we own

**Pull request merged**
