### PR TITLE
to support how we work: work structure

### PR DESCRIPTION
**Pull request by its-a-lisa-at-work**
To support: https://github.com/18F/tts-tech-portfolio/issues/469

### CODE REVIEW

**Comment by its-a-lisa-at-work** [comment]
@afeld nudge

**Comment by its-a-lisa-at-work** [comment]
closes https://github.com/18F/tts-tech-portfolio/issues/469; all changes from the [document](https://docs.google.com/document/d/1tj0Ll8x7OkBtilJQKqkWqVhd_spByEm21n84g6mW0-w/edit#) are in this pull request now and the document is no longer relevant.

**Comment by afeld** [comment]
@JJediny I'm ok with us having more labels that actually get use, but otherwise, agree with @its-a-lisa-at-work that we should remove for the sake of keeping things tidy.

**Comment by afeld** [comment]
`apply`'d! Script used to migrate the labels:

```python
old_to_new_labels = {
    "groomed: delegate": "dg: delegate",
    "groomed: decide": "dg: decide",
    "groomed: accepted": "g: accepted",
    "groomed: draft - final": "g: final",
    "grooming: draft - initial": "g: initial",
    "expedite": "t: expedite",
    "size: days": "t: days",
    "size: hours": "t: hours",
    "size: months": "t: months",
    "size: weeks": "t: weeks",
    "due date": "m: due date",
    "feedback needed": "m: feedback needed",
    "blog-able": "a: blog-able",
    "demo-able": "a: demo-able",
    # "": "i: SaaS authorizations",
    # "": "i: infrastructure improvement",
    "epic: acquisition procurement and budgeting": "i: acquisition",
    # "": "i: communication",
    "internal workflow": "i: internal workflow",
    # "": "i: mac",
    # "": "i: enterprise architecture",
    # "": "i: bug bounty",
    # "": "i: misc",
    # "": "e: aws cleanup",
    # "": "e: bb expansion",
    # "": "e: SaaS documentation",
}

repos = [
    "aws-admin",
    "before-you-ship",
    "bug-bounty",
    "dns",
    "ghad",
    "handbook",
    "laptop",
    "tts-tech-portfolio-private",
    "tts-tech-portfolio",
    "vulnerability-disclosure-policy",
]

for repo in repos:
    for old, new in old_to_new_labels.items():
        print(
            f"terraform state mv 'github_issue_label.{repo}[\"{old}\"]' 'github_issue_label.{repo}[\"{new}\"]'"
        )
```

**Pull request merged**
