### PR TITLE
update w/ anonymous form

### PR DESCRIPTION
**Pull request by its-a-lisa**
Documenting the Anonymous TTS Tech Portfolio form within the OpsRotation checklist to support https://github.com/18F/tts-tech-portfolio/issues/144

### CODE REVIEW

**Comment by afeld** [comment]
Since it's every two weeks, should we just do this as an automated reminder in Slack?

**Comment by its-a-lisa** [comment]
I see the difference between having it in the checklist vs a slack reminder is checklist -- inward facing to check the responses and slack reminder -- outward facing to have the folks provide submission

**Comment by afeld** [comment]
Should we change this to being "check the form responses" then?

**Comment by its-a-lisa** [comment]
ya, that seems better to have in the checklist -- sorry, I got confused with my response before.

**Comment by its-a-lisa** [comment]
@afeld nudge

**Pull request merged**
