### PR TITLE
Update onboarding.md

### PR DESCRIPTION
**Pull request by adborden**
I don't have access to the docs linked and it seems that no one else has access to them either. I wanted to do a little digging before merging (maybe the content moved?).

### CODE REVIEW

**Comment by JJediny** [comment]
I dont have access either, which tells me its a bad link to our team shared drive https://drive.google.com/drive/folders/0AK0cBcPVg19cUk9PVA

Suggest undrafting and merging

**Comment by JJediny** [comment]
Terraform plan in __terraform__
<details>
  <summary>No changes. Your infrastructure matches the configuration.</summary>

```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```
</details>

Plan generated in [plan #21](https://github.com/18F/tts-tech-portfolio/actions/runs/971953352)

**Comment by adborden** [comment]
Leaving as a draft since there's still some digging I'd like to do.

**Comment by adborden** [comment]
Confirmed that this is the cloud.gov team drive, and therefore it does not make sense to include it here. I also removed the cloud.gov IR training link for the same reason.

Under the "Thinks we maintain" heading, there is now a list of one element. Should I make it not a list? Since the section is incomplete, should I try adding additional things to make it complete, or should I just remove the section altogether?

**Review by rocheller123 — COMMENTED** [review]
The BYS link redirects to https://handbook.tts.gsa.gov/#launching-software. Should it just be replaced with the new "Launching software" link?

**Comment by adborden** [comment]
@rocheller123 yep! I'll address that in the next PR https://github.com/18F/tts-tech-portfolio/pull/1425

**Review by rocheller123 — APPROVED** [review]

**Review by JJediny — APPROVED** [review]
LG

**Pull request merged**
