### PR TITLE
add Tech Portfolio members to GitHub organizations via code

### PR DESCRIPTION
**Pull request by afeld**
Closes https://github.com/18F/tts-tech-portfolio/issues/83.

Questions:

- Something going wrong with the `apply` could remove all of us from the orgs. Are we ok with that risk?
- The source list of usernames is the @18F/tts-tech-portfolio team. Should we keep it that way, or flip it around so that team is created via code? (Could happen in a separate pull request.)

### CODE REVIEW

**Comment by JJediny** [comment]
Terraform plan in __terraform__
<details>
  <summary>Plan: 56 to add, 0 to change, 0 to destroy.</summary>

```hcl
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # local_file.github_repos will be created
  + resource "local_file" "github_repos" {
      + content              = <<-EOT
            _This file is generated by [Terraform](../terraform/github.md.tmpl)._
            
            # GitHub Repos
            
            | repo | status | Tech Portfolio manages all content? |
            | --- | --- | --- |
            | [18F/.github](https://github.com/18F/.github) | active | N |
            | [18F/aws-admin](https://github.com/18F/aws-admin) | active | Y |
            | [18F/aws-admin-cleanup](https://github.com/18F/aws-admin-cleanup) | active | Y |
            | [18F/before-you-ship](https://github.com/18F/before-you-ship) | archived | Y |
            | [18F/billing-tools](https://github.com/18F/billing-tools) | archived | Y |
            | [18F/bug-bounty](https://github.com/18F/bug-bounty) | active | Y |
            | [18F/certificate-service](https://github.com/18F/certificate-service) | archived | Y |
            | [18F/chandika](https://github.com/18F/chandika) | archived | Y |
            | [18F/charlie](https://github.com/18F/charlie) | active | Y |
            | [18F/chat](https://github.com/18F/chat) | active | Y |
            | [18F/deploy-ttslicenses](https://github.com/18F/deploy-ttslicenses) | archived | Y |
            | [18F/dns](https://github.com/18F/dns) | active | N |
            | [18F/ghad](https://github.com/18F/ghad) | active | Y |
            | [18F/handbook](https://github.com/18F/handbook) | active | N |
            | [18F/join.tts.gsa.gov](https://github.com/18F/join.tts.gsa.gov) | active | N |
            | [18F/laptop](https://github.com/18F/laptop) | archived | Y |
            | [18F/newrelic-terraform](https://github.com/18F/newrelic-terraform) | active | Y |
            | [18F/pages-redirects](https://github.com/18F/pages-redirects) | active | Y |
            | [18F/private-eye](https://github.com/18F/private-eye) | active | Y |
            | [18F/raktabija](https://github.com/18F/raktabija) | archived | Y |
            | [18F/slack-export-handling](https://github.com/18F/slack-export-handling) | archived | Y |
            | [18F/tts-common-controls](https://github.com/18F/tts-common-controls) | active | Y |
            | [18F/tts-tech-portfolio](https://github.com/18F/tts-tech-portfolio) | active | Y |
            | [18F/tts-tech-portfolio-private](https://github.com/18F/tts-tech-portfolio-private) | active | Y |
            | [18F/uswds-jekyll](https://github.com/18F/uswds-jekyll) | active | Y |
            | [18F/vulnerability-disclosure-policy](https://github.com/18F/vulnerability-disclosure-policy) | active | Y |
            
            For repositories where the Tech Portfolio _doesn't_ manage all content, we are the "technical owners", meaning we keep them running, fix any security vulnerabilities, etc. In the Handbook, we are responsible for pages related to things we own, like those under [software and tools](https://handbook.tts.gsa.gov/#software-and-tools).
            
            ## Adding a repository
            
            When a repository is considered "managed" by the Tech Portfolio, it should be included in the following places:
            
            - [The list in Terraform](../terraform/main.tf)
            - Linked repositories for project boards
              - [Team board](https://github.com/orgs/18F/projects/11/settings/linked_repositories)
              - [Pull requests](https://github.com/orgs/18F/projects/19/settings/linked_repositories)
        EOT
      + directory_permission = "0755"
      + file_permission      = "0644"
      + filename             = "./../how_we_work/github.md"
      + id                   = (known after apply)
    }

  # module.cloud_gov.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.cloud_gov.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.cloud_gov.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.cloud_gov.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.cloud_gov.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.digital_analytics_program.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.digital_analytics_program.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.digital_analytics_program.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.digital_analytics_program.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.digital_analytics_program.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.digitalgov.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.digitalgov.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.digitalgov.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.digitalgov.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.digitalgov.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.federalist_users.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.federalist_users.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.federalist_users.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.federalist_users.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.federalist_users.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.fedramp.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.fedramp.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.fedramp.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.fedramp.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.fedramp.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.fellows_in_innovation.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.fellows_in_innovation.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.fellows_in_innovation.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.fellows_in_innovation.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.fellows_in_innovation.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.org_18f.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.org_18f.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.org_18f.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.org_18f.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.org_18f.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.presidential_innovation_fellows.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.presidential_innovation_fellows.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.presidential_innovation_fellows.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.presidential_innovation_fellows.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.presidential_innovation_fellows.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.project_open_data.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.project_open_data.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.project_open_data.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.project_open_data.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.project_open_data.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.usagov.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.usagov.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.usagov.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.usagov.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.usagov.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

  # module.uswds.github_membership.owner["JJediny"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "JJediny"
    }

  # module.uswds.github_membership.owner["adborden"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "adborden"
    }

  # module.uswds.github_membership.owner["afeld"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "afeld"
    }

  # module.uswds.github_membership.owner["rocheller123"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "rocheller123"
    }

  # module.uswds.github_membership.owner["tts-bot"] will be created
  + resource "github_membership" "owner" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "tts-bot"
    }

Plan: 56 to add, 0 to change, 0 to destroy.
```
</details>

Plan generated in [plan #71](https://github.com/18F/tts-tech-portfolio/actions/runs/1052903479)

**Review by JJediny — APPROVED** [review]
nice lgtm

**Comment by afeld** [comment]
It worked!

Screen Shot 2021-07-22 at 12 57 43 PM

…except where [it didn't](https://github.com/18F/tts-tech-portfolio/runs/3136130968?check_suite_focus=true#step:4:1026).

**Comment by afeld** [comment]
Fixing (most) in https://github.com/18F/tts-tech-portfolio/pull/1474.

**Pull request merged**
