### PR TITLE
clean up issue templates

### PR DESCRIPTION
**Pull request by afeld**
- Remove the Basic issue template
   - Didn't seem to be getting used, and wasn't clear when to use it
- Remove the User Stories from the General issue template
   - Seems that answering the "what problem are we trying to solve?" question has been more useful for us
- Formatted all Markdown files using Prettier

Easiest to [view the diff ignoring whitespace](https://github.com/18F/tts-tech-portfolio/pull/406/files?w=1). I propose we use this format going forward for new(ly groomed) issues, but don't bother modifying already-groomed issues.

### CODE REVIEW

**Comment by its-a-lisa** [comment]
> Remove the Basic issue template
> Didn't seem to be getting used, and wasn't clear when to use it

Rather than remove it, I would rather have a discussion on when best to use it. I think there are definitely cards that should be on the board that aren't (quick turn around tasks, task from working groups, etc) that could benefit from not having to have a major effort associated with them and make the barrier to entry more palatable. 

> Formatted all Markdown files using Prettier

We should probably have using Prettier in some 'Best Practice' place

> Remove the User Stories from the General issue template
> Seems that answering the "what problem are we trying to solve?" question has been more useful for us

I would still like to get User Story training and probably for us to spend more time on how the user affects us. Also, I think we need to have a separate place/space for collecting user stories since they're all broken up and scattered and no rolling record of them. Also, I have seen several different version on how to phrase user stories (like what was written on the white board that time) so rather than eliminate it, I think we should more time refining it and figuring out what works best for us. 

> Implementation is prescriptive which is an anti-pattern of solving the user story with upfront assumptions. 

I hadn't thought of that before, but I can see your point. 
Although, what is important to me with the implementation steps is that it shows some pre-thought into how the person assigned to the card is going to solve the issue and the steps that person is going to take to address it. I see it mostly as a communication method to the rest of the team as a method of letting everyone else know what is being done with the issue and a preemptive way for each of us to know what the others are doing. Also, it gives other people on the team a chance to provide input and collaborate on how to solve the issue despite not being the ones working on it; assuming that work doesn't start until the `grooming: accepted `label is met. 

When I think of `acceptance criteria`, I think about 'under what circumstances is it OK to close this card' -- I feel like in the last Sprint, there were some cards that had finished the implementation steps and had met the acceptance criteria, but there was reluctance to close the card. I feel like that is an indication that we're not all on the same page or that the card didn't really state what was trying to be addressed in the first place.

**Comment by afeld** [comment]
> We should probably have using Prettier in some 'Best Practice' place

Adding in https://github.com/18F/tts-tech-portfolio/pull/412.

> what is important to me with the implementation steps is that it shows some pre-thought into how the person assigned to the card is going to solve the issue and the steps that person is going to take to address it

Agree. If the cards are small enough, the steps to complete it should be pretty clear, though what will go into the follow-up issues may not be.

**Comment by afeld** [comment]
Great feedback from @mogul (posted with permission):

> Suggestion: Implementation should go **after** the ACs in your story template. This helps you avoid the temptation to talk about what you're going to do before you talk about your goals and how you know you'll be successful. Working out ACs first also means you're more likely to find a good place for breaking the story into multiple smaller ones that could be tackled independently.
>
> Also suggest replacing "Implementation" with "Sketch" to avoid everyone feeling they need to concretely know exactly how things are going to work, and people who weren't there at the writing assuming that everything is concrete during the reading.

**Comment by afeld** [comment]
Took @mogul's advice and made a new pull request: https://github.com/18F/tts-tech-portfolio/pull/456

**Pull request closed without merging**
