### PR TITLE
Archive Before You Ship 

### PR DESCRIPTION
**Pull request by dylanirlbeck**

### CODE REVIEW

**Comment by JJediny** [comment]
Terraform plan in __terraform__
<details>
  <summary>Plan: 1 to add, 0 to change, 0 to destroy.</summary>

```hcl
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # local_file.github_repos will be created
  + resource "local_file" "github_repos" {
      + content              = <<-EOT
            <!-- this file is generated by Terraform -->
            
            # GitHub Repos
            
            | repo | status | Tech Portfolio manages all content? |
            | --- | --- | --- |
            | [18F/aws-admin](https://github.com/18F/aws-admin) | active | Y |
            | [18F/aws-admin-cleanup](https://github.com/18F/aws-admin-cleanup) | active | Y |
            | [18F/before-you-ship](https://github.com/18F/before-you-ship) | active | Y |
            | [18F/billing-tools](https://github.com/18F/billing-tools) | archived | Y |
            | [18F/bug-bounty](https://github.com/18F/bug-bounty) | active | Y |
            | [18F/certificate-service](https://github.com/18F/certificate-service) | archived | Y |
            | [18F/chandika](https://github.com/18F/chandika) | archived | Y |
            | [18F/charlie](https://github.com/18F/charlie) | active | Y |
            | [18F/chat](https://github.com/18F/chat) | active | Y |
            | [18F/deploy-ttslicenses](https://github.com/18F/deploy-ttslicenses) | archived | Y |
            | [18F/dns](https://github.com/18F/dns) | active | N |
            | [18F/ghad](https://github.com/18F/ghad) | active | Y |
            | [18F/handbook](https://github.com/18F/handbook) | active | N |
            | [18F/join.tts.gsa.gov](https://github.com/18F/join.tts.gsa.gov) | active | N |
            | [18F/laptop](https://github.com/18F/laptop) | archived | Y |
            | [18F/newrelic-terraform](https://github.com/18F/newrelic-terraform) | active | Y |
            | [18F/pages-redirects](https://github.com/18F/pages-redirects) | active | Y |
            | [18F/private-eye](https://github.com/18F/private-eye) | active | Y |
            | [18F/raktabija](https://github.com/18F/raktabija) | archived | Y |
            | [18F/slack-export-handling](https://github.com/18F/slack-export-handling) | archived | Y |
            | [18F/tts-common-controls](https://github.com/18F/tts-common-controls) | active | Y |
            | [18F/tts-tech-portfolio](https://github.com/18F/tts-tech-portfolio) | active | Y |
            | [18F/tts-tech-portfolio-private](https://github.com/18F/tts-tech-portfolio-private) | active | Y |
            | [18F/uswds-jekyll](https://github.com/18F/uswds-jekyll) | active | Y |
            | [18F/vulnerability-disclosure-policy](https://github.com/18F/vulnerability-disclosure-policy) | active | Y |
            
            For repositories where the Tech Portfolio _doesn't_ manage all content, we are the "technical owners", meaning we keep them running, fix any security vulnerabilities, etc. In the Handbook, we are responsible for pages related to things we own, like those under [software and tools](https://handbook.tts.gsa.gov/#software-and-tools).
            
            ## Adding a repository
            
            When a repository is considered "managed" by the Tech Portfolio, it should be included in the following places:
            
            - [The list in Terraform](../terraform/main.tf)
            - Linked repositories for project boards
              - [Team board](https://github.com/orgs/18F/projects/11/settings/linked_repositories)
              - [Pull requests](https://github.com/orgs/18F/projects/19/settings/linked_repositories)
        EOT
      + directory_permission = "0755"
      + file_permission      = "0644"
      + filename             = "./../how_we_work/github.md"
      + id                   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
</details>

Plan generated in [plan #35](https://github.com/18F/tts-tech-portfolio/actions/runs/984495351)

**Comment by adborden** [comment]
This page is auto-generated, try adding the archived flag here instead https://github.com/18F/tts-tech-portfolio/blob/main/terraform/main.tf#L27

**Comment by adborden** [comment]
Hopefully this will make it more obvious that this page is autogenerated https://github.com/18F/tts-tech-portfolio/pull/1414

**Review by afeld — APPROVED** [review]
Let's wait to merge until https://github.com/18F/before-you-ship/issues/539 is done.

**Pull request merged**
